# Etapa 1: Build
FROM node:20-alpine AS builder
WORKDIR /app

# Recibe las variables de entorno en tiempo de build
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_N8N_INVOICE_WEBHOOK
ARG VITE_N8N_AGREEMENT_WEBHOOK
ARG VITE_N8N_WEBHOOK_TOKEN
ARG VITE_N8N_CREATE_USER_WEBHOOK
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_N8N_INVOICE_WEBHOOK=$VITE_N8N_INVOICE_WEBHOOK
ENV VITE_N8N_AGREEMENT_WEBHOOK=$VITE_N8N_AGREEMENT_WEBHOOK
ENV VITE_N8N_WEBHOOK_TOKEN=$VITE_N8N_WEBHOOK_TOKEN
ENV VITE_N8N_CREATE_USER_WEBHOOK=$VITE_N8N_CREATE_USER_WEBHOOK

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Etapa 2: Serve con Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]